In [10]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [11]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [16]:
movies = pd.read_csv(r"C:\Users\hp\Downloads\Movie+Assignment+Data (2).csv")
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [17]:
# Write your code for inspection here
movies.shape

(5043, 28)

In [18]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [20]:
movies.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [21]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [22]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [23]:
# Write your code for column-wise null percentages here
color
director_facebook_likes
actor_1_facebook_likes
actor_2_facebook_likes
actor_3_facebook_likes
actor_2_name
cast_total_facebook_likes
actor_3_name
duration
facenumber_in_poster
content_rating
country
movie_imdb_link
aspect_ratio
plot_keywords

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.28
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [25]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies=movies.drop(["color",
                    "director_facebook_likes",
                     "actor_1_facebook_likes",
                     "actor_2_facebook_likes",
                     "actor_3_facebook_likes",
                      "actor_2_name",
                      "cast_total_facebook_likes",
                      "actor_3_name",
                       "duration",
                       "facenumber_in_poster",
                       "content_rating",
                        "country",
                        "movie_imdb_link",
                       "aspect_ratio",
                        "plot_keywords"],
                         axis=1)

In [26]:
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

In [27]:
movies.shape

(5043, 13)

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [28]:
# inspecting the percentage of null values again
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name              2.06
num_critic_for_reviews     0.99
gross                     17.53
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.42
language                   0.28
budget                     9.76
title_year                 2.14
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

In [29]:
# Write your code for dropping the rows here
movies=movies[~np.isnan(movies["gross"])]
movies= movies[~np.isnan(movies["budget"])]
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

In [34]:
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.10
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

Subtask 2.4: Drop unecessary rows
#Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [44]:
movies=movies[~movies.isnull().sum(axis=1) <=5]
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

In [45]:
round(100*(movies1.isnull().sum()/len(movies1.index)),2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.10
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [46]:
# Write your code for filling the NaN values in the 'language' column here
movies["language"].describe()

count        3887
unique         37
top       English
freq         3707
Name: language, dtype: object

In [48]:
movies.loc[pd.isnull(movies["language"]),["language"]]="English"
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

In [50]:
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [51]:
# Write your code for checking number of retained rows here
print(len(movies.index))
print(len(movies.index)/5042)

3891
0.771717572391908

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [53]:
# Write your code for unit conversion here
movies["gross"]= movies["gross"]/1000000
movies["budget"]=movies["budget"]/1000000
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,7.605058e-04,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,2.370000e-04,2009.0,7.9,33000
1,Gore Verbinski,302.0,3.094042e-04,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,3.000000e-04,2007.0,7.1,0
2,Sam Mendes,602.0,2.000742e-04,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,2.450000e-04,2015.0,6.8,85000
3,Christopher Nolan,813.0,4.481306e-04,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,2.500000e-04,2012.0,8.5,164000
5,Andrew Stanton,462.0,7.305868e-05,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,2.637000e-04,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,4.247600e-07,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7.000000e-09,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,7.007100e-08,Thriller,Ian Gamazon,Cavite,589,35.0,English,7.000000e-09,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920e-06,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7.000000e-09,1992.0,6.9,0
5037,Edward Burns,14.0,4.584000e-09,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9.000000e-09,2011.0,6.4,413
5042,Jon Gunn,43.0,8.522200e-08,Documentary,John August,My Date with Drew,4285,84.0,English,1.100000e-09,2004.0,6.6,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [55]:
# Write your code for creating the profit column here
movies["Profit"]=movies["gross"]-movies["budget"]
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,7.605058e-04,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,2.370000e-04,2009.0,7.9,33000,5.235058e-04
1,Gore Verbinski,302.0,3.094042e-04,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,3.000000e-04,2007.0,7.1,0,9.404152e-06
2,Sam Mendes,602.0,2.000742e-04,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,2.450000e-04,2015.0,6.8,85000,-4.492583e-05
3,Christopher Nolan,813.0,4.481306e-04,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,2.500000e-04,2012.0,8.5,164000,1.981306e-04
5,Andrew Stanton,462.0,7.305868e-05,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,2.637000e-04,2012.0,6.6,24000,-1.906413e-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,4.247600e-07,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7.000000e-09,2004.0,7.0,19000,4.177600e-07
5034,Neill Dela Llana,35.0,7.007100e-08,Thriller,Ian Gamazon,Cavite,589,35.0,English,7.000000e-09,2005.0,6.3,74,6.307100e-08
5035,Robert Rodriguez,56.0,2.040920e-06,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7.000000e-09,1992.0,6.9,0,2.033920e-06
5037,Edward Burns,14.0,4.584000e-09,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9.000000e-09,2011.0,6.4,413,-4.416000e-09
5042,Jon Gunn,43.0,8.522200e-08,Documentary,John August,My Date with Drew,4285,84.0,English,1.100000e-09,2004.0,6.6,456,8.412200e-08

In [58]:
# Write your code for sorting the dataframe here
movies= movies.sort_values(by="Profit",ascending=False)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,7.605058e-04,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,0.000237,2009.0,7.9,33000,0.000524
29,Colin Trevorrow,644.0,6.521773e-04,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,0.000150,2015.0,7.0,150000,0.000502
26,James Cameron,315.0,6.586723e-04,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,0.000200,1997.0,7.7,26000,0.000459
3024,George Lucas,282.0,4.609357e-04,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,0.000011,1977.0,8.7,33000,0.000450
3080,Steven Spielberg,215.0,4.349495e-04,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,0.000010,1982.0,7.9,34000,0.000424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,4.103880e-07,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,0.002128,2004.0,6.9,973,-0.002127
2323,Hayao Miyazaki,174.0,2.298191e-06,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,0.002400,1997.0,8.4,11000,-0.002398
3005,Lajos Koltai,73.0,1.958880e-07,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,0.002500,2005.0,7.1,607,-0.002500
3859,Chan-wook Park,202.0,2.116670e-07,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,0.004200,2005.0,7.7,4000,-0.004200
2988,Joon-ho Bong,363.0,2.201412e-06,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,0.012216,2006.0,7.0,7000,-0.012213

In [59]:
top10 = movies.iloc[:10,] # Write your code to get the top 10 profiting movies here
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,0.000761,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,0.000237,2009.0,7.9,33000,0.000524
29,Colin Trevorrow,644.0,0.000652,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,0.000150,2015.0,7.0,150000,0.000502
26,James Cameron,315.0,0.000659,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,0.000200,1997.0,7.7,26000,0.000459
3024,George Lucas,282.0,0.000461,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,0.000011,1977.0,8.7,33000,0.000450
3080,Steven Spielberg,215.0,0.000435,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,0.000010,1982.0,7.9,34000,0.000424
794,Joss Whedon,703.0,0.000623,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,0.000220,2012.0,8.1,123000,0.000403
17,Joss Whedon,703.0,0.000623,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,0.000220,2012.0,8.1,123000,0.000403
509,Roger Allers,186.0,0.000423,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,0.000045,1994.0,8.5,17000,0.000378
240,George Lucas,320.0,0.000475,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,0.000115,1999.0,6.5,13000,0.000360
66,Christopher Nolan,645.0,0.000533,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,0.000185,2008.0,9.0,37000,0.000348

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [62]:
# Write your code for dropping duplicate values here
movies.drop_duplicates(subset=None,keep="first",inplace=True)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,7.605058e-04,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,0.000237,2009.0,7.9,33000,0.000524
29,Colin Trevorrow,644.0,6.521773e-04,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,0.000150,2015.0,7.0,150000,0.000502
26,James Cameron,315.0,6.586723e-04,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,0.000200,1997.0,7.7,26000,0.000459
3024,George Lucas,282.0,4.609357e-04,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,0.000011,1977.0,8.7,33000,0.000450
3080,Steven Spielberg,215.0,4.349495e-04,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,0.000010,1982.0,7.9,34000,0.000424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,4.103880e-07,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,0.002128,2004.0,6.9,973,-0.002127
2323,Hayao Miyazaki,174.0,2.298191e-06,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,0.002400,1997.0,8.4,11000,-0.002398
3005,Lajos Koltai,73.0,1.958880e-07,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,0.002500,2005.0,7.1,607,-0.002500
3859,Chan-wook Park,202.0,2.116670e-07,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,0.004200,2005.0,7.7,4000,-0.004200
2988,Joon-ho Bong,363.0,2.201412e-06,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,0.012216,2006.0,7.0,7000,-0.012213

In [63]:
# Write code for repeating subtask 2 here
top10= movies.iloc[:10,]
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit
0,James Cameron,723.0,0.000761,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,0.000237,2009.0,7.9,33000,0.000524
29,Colin Trevorrow,644.0,0.000652,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,0.000150,2015.0,7.0,150000,0.000502
26,James Cameron,315.0,0.000659,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,0.000200,1997.0,7.7,26000,0.000459
3024,George Lucas,282.0,0.000461,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,0.000011,1977.0,8.7,33000,0.000450
3080,Steven Spielberg,215.0,0.000435,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,0.000010,1982.0,7.9,34000,0.000424
794,Joss Whedon,703.0,0.000623,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,0.000220,2012.0,8.1,123000,0.000403
509,Roger Allers,186.0,0.000423,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,0.000045,1994.0,8.5,17000,0.000378
240,George Lucas,320.0,0.000475,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,0.000115,1999.0,6.5,13000,0.000360
66,Christopher Nolan,645.0,0.000533,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,0.000185,2008.0,9.0,37000,0.000348
439,Gary Ross,673.0,0.000408,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,0.000078,2012.0,7.3,140000,0.000330

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [65]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
top_250=movies.sort_values(by="imdb_score",ascending=False)
top_250= top_250.loc[top_250.num_voted_users >25000]
top_250= top_250.iloc[:250,]
top_250["Rank"]=range(1,251)
top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,Rank
1937,Frank Darabont,199.0,2.834147e-05,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,0.000025,1994.0,9.3,108000,0.000003,1
3466,Francis Ford Coppola,208.0,1.348220e-04,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,0.000006,1972.0,9.2,43000,0.000129,2
66,Christopher Nolan,645.0,5.333161e-04,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,0.000185,2008.0,9.0,37000,0.000348,3
2837,Francis Ford Coppola,149.0,5.730000e-05,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,0.000013,1974.0,9.0,14000,0.000044,4
339,Peter Jackson,328.0,3.770193e-04,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,0.000094,2003.0,8.9,16000,0.000283,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,Cameron Crowe,149.0,3.252235e-05,Adventure|Comedy|Drama|Music,Philip Seymour Hoffman,Almost Famous,207287,822.0,English,0.000060,2000.0,7.9,15000,-0.000027,246
99,Peter Jackson,645.0,3.030012e-04,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected Journey,637246,1367.0,English,0.000180,2012.0,7.9,166000,0.000123,247
1606,Nick Cassavetes,177.0,6.428600e-08,Drama|Romance,Ryan Gosling,The Notebook,396396,1111.0,English,0.000029,2004.0,7.9,57000,-0.000029,248
1735,James Mangold,291.0,1.195184e-04,Biography|Drama|Music|Romance,Sandra Ellis Lafferty,Walk the Line,188637,815.0,English,0.000028,2005.0,7.9,11000,0.000092,249
639,Michael Mann,209.0,2.896520e-05,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,0.000068,1999.0,7.9,0,-0.000039,250

In [66]:
Top_Foreign_Lang_Film = top_250.loc[top_250["language"]!="English"]
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,Rank
4498,Sergio Leone,181.0,6.100000e-06,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000e-06,1966.0,8.9,20000,4.900000e-06,7
4029,Fernando Meirelles,214.0,7.563397e-06,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000e-06,2002.0,8.7,28000,4.263397e-06,17
4747,Akira Kurosawa,153.0,2.690610e-07,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000e-06,1954.0,8.7,11000,-1.730939e-06,19
2373,Hayao Miyazaki,246.0,1.004989e-05,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,1.900000e-05,2001.0,8.6,28000,-8.950114e-06,22
4259,Florian Henckel von Donnersmarck,215.0,1.128466e-05,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000e-06,2006.0,8.5,39000,9.284657e-06,29
4921,Majid Majidi,46.0,9.254020e-07,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,1.800000e-07,1997.0,8.5,0,7.454020e-07,32
1298,Jean-Pierre Jeunet,242.0,3.320166e-05,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,7.700000e-05,2001.0,8.4,39000,-4.379834e-05,48
4105,Chan-wook Park,305.0,2.181290e-06,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000e-06,2003.0,8.4,43000,-8.187100e-07,55
4659,Asghar Farhadi,354.0,7.098492e-06,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,5.000000e-07,2011.0,8.4,48000,6.598492e-06,56
2970,Wolfgang Petersen,96.0,1.143313e-05,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,1.400000e-05,1981.0,8.4,11000,-2.566866e-06,59
2323,Hayao Miyazaki,174.0,2.298191e-06,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e-03,1997.0,8.4,11000,-2.397702e-03,60
1329,S.S. Rajamouli,44.0,6.498000e-06,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,1.802615e-05,2015.0,8.4,21000,-1.152815e-05,61
4033,Thomas Vinterberg,349.0,6.109680e-07,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000e-06,2012.0,8.3,60000,-3.189032e-06,72
2829,Oliver Hirschbiegel,192.0,5.501940e-06,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,1.350000e-05,2004.0,8.3,14000,-7.998060e-06,78
2734,Fritz Lang,260.0,2.643500e-08,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000e-06,1927.0,8.3,12000,-5.973565e-06,84
3550,Denis Villeneuve,226.0,6.857096e-06,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000e-06,2010.0,8.2,37000,5.709600e-08,91
4000,Juan José Campanella,262.0,2.016742e-05,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000e-06,2009.0,8.2,33000,1.816742e-05,92
2047,Hayao Miyazaki,212.0,4.710455e-06,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,2.400000e-05,2004.0,8.2,13000,-1.928955e-05,94
2551,Guillermo del Toro,406.0,3.762314e-05,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,1.350000e-05,2006.0,8.2,27000,2.412314e-05,102
3553,José Padilha,142.0,8.060000e-09,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000e-06,2007.0,8.1,11000,-3.991940e-06,108
2914,Je-kyu Kang,86.0,1.110186e-06,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,1.280000e-05,2004.0,8.1,0,-1.168981e-05,121
2830,Alejandro Amenábar,157.0,2.086345e-06,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,1.000000e-05,2004.0,8.1,0,-7.913655e-06,124
4267,Alejandro G. Iñárritu,157.0,5.383834e-06,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000e-06,2000.0,8.1,11000,3.383834e-06,132
3423,Katsuhiro Ôtomo,150.0,4.391620e-07,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1.100000e-03,1988.0,8.1,0,-1.099561e-03,138
4461,Thomas Vinterberg,98.0,1.647780e-06,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000e-06,1998.0,8.1,5000,3.477800e-07,139
3344,Karan Johar,210.0,4.018695e-06,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,1.200000e-05,2010.0,8.0,27000,-7.981305e-06,157
4284,Ari Folman,231.0,2.283276e-06,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000e-06,2008.0,8.0,0,7.832760e-07,183
3456,Vincent Paronnaud,242.0,4.443403e-06,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000e-06,2007.0,8.0,14000,-2.856597e-06,184
4144,Walter Salles,71.0,5.595428e-06,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000e-06,1998.0,8.0,0,2.695428e-06,193
4897,Sergio Leone,122.0,3.500000e-06,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,2.000000e-07,1964.0,8.0,0,3.300000e-06,200
3677,Christophe Barratier,112.0,3.629758e-06,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.500000e-06,2004.0,7.9,0,-1.870242e-06,206
4640,Cristian Mungiu,233.0,1.185783e-06,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,5.900000e-07,2007.0,7.9,14000,5.957830e-07,208
4415,Fabián Bielinsky,94.0,1.221261e-06,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.500000e-06,2000.0,7.9,0,-2.787390e-07,215
2863,Clint Eastwood,251.0,1.375393e-05,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,1.900000e-05,2006.0,7.9,5000,-5.246069e-06,221
3510,Yash Chopra,29.0,2.921738e-06,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.000000e-06,2004.0,7.9,2000,-4.078262e-06,228
3264,Michael Haneke,447.0,2.253770e-07,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.900000e-06,2012.0,7.9,33000,-8.674623e-06,230

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [68]:
# Write your code for extracting the top 10 directors here
directors= movies.pivot_table(values="imdb_score",index="director_name",aggfunc="mean")
directors= directors.sort_values(by= "imdb_score",ascending=False)
directors=directors.iloc[:10,]
directors

                       imdb_score
director_name
Charles Chaplin          8.600000
Tony Kaye                8.600000
Alfred Hitchcock         8.500000
Ron Fricke               8.500000
Damien Chazelle          8.500000
Majid Majidi             8.500000
Sergio Leone             8.433333
Christopher Nolan        8.425000
S.S. Rajamouli           8.400000
Marius A. Markevicius    8.400000

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [69]:
# Write your code for extracting the first two genres of each movie here
movies["genres"]=movies["genres"].str.split("|")
movies["genre_1"]=movies["genres"].apply(lambda x: x[0])
movies["genre_2"]=movies["genres"].apply(lambda x:x[1] if len(x) > 1 else x[0])
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
0,James Cameron,723.0,7.605058e-04,"[Action, Adventure, Fantasy, Sci-Fi]",CCH Pounder,Avatar,886204,3054.0,English,0.000237,2009.0,7.9,33000,0.000524,Action,Adventure
29,Colin Trevorrow,644.0,6.521773e-04,"[Action, Adventure, Sci-Fi, Thriller]",Bryce Dallas Howard,Jurassic World,418214,1290.0,English,0.000150,2015.0,7.0,150000,0.000502,Action,Adventure
26,James Cameron,315.0,6.586723e-04,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,0.000200,1997.0,7.7,26000,0.000459,Drama,Romance
3024,George Lucas,282.0,4.609357e-04,"[Action, Adventure, Fantasy, Sci-Fi]",Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,0.000011,1977.0,8.7,33000,0.000450,Action,Adventure
3080,Steven Spielberg,215.0,4.349495e-04,"[Family, Sci-Fi]",Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,0.000010,1982.0,7.9,34000,0.000424,Family,Sci-Fi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,4.103880e-07,"[Action, Adventure, Animation, Family, Sci-Fi,...",William Hootkins,Steamboy,13727,79.0,Japanese,0.002128,2004.0,6.9,973,-0.002127,Action,Adventure
2323,Hayao Miyazaki,174.0,2.298191e-06,"[Adventure, Animation, Fantasy]",Minnie Driver,Princess Mononoke,221552,570.0,Japanese,0.002400,1997.0,8.4,11000,-0.002398,Adventure,Animation
3005,Lajos Koltai,73.0,1.958880e-07,"[Drama, Romance, War]",Marcell Nagy,Fateless,5603,45.0,Hungarian,0.002500,2005.0,7.1,607,-0.002500,Drama,Romance
3859,Chan-wook Park,202.0,2.116670e-07,"[Crime, Drama]",Min-sik Choi,Lady Vengeance,53508,131.0,Korean,0.004200,2005.0,7.7,4000,-0.004200,Crime,Drama
2988,Joon-ho Bong,363.0,2.201412e-06,"[Comedy, Drama, Horror, Sci-Fi]",Doona Bae,The Host,68883,279.0,Korean,0.012216,2006.0,7.0,7000,-0.012213,Comedy,Drama

In [70]:
movies_by_segment = movies.groupby(["genre_1","genre_2"])

In [71]:
PopGenre = pd.DataFrame(movies_by_segment["gross"].mean()).sort_values(by = "gross",ascending=False)
PopGenre.iloc[:5,]

                        gross
genre_1   genre_2
Family    Sci-Fi     0.000435
Adventure Sci-Fi     0.000229
          Family     0.000119
          Animation  0.000117
Action    Adventure  0.000110

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [74]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies.loc[movies.actor_1_name=="Meryl Streep"]
Meryl_Streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
1408,David Frankel,208.0,0.000125,"[Comedy, Drama, Romance]",Meryl Streep,The Devil Wears Prada,286178,631.0,English,0.000035,2006.0,6.8,0,0.000090,Comedy,Drama
1575,Sydney Pollack,66.0,0.000087,"[Biography, Drama, Romance]",Meryl Streep,Out of Africa,52339,200.0,English,0.000031,1985.0,7.2,0,0.000056,Biography,Drama
1204,Nora Ephron,252.0,0.000094,"[Biography, Drama, Romance]",Meryl Streep,Julie & Julia,79264,277.0,English,0.000040,2009.0,7.0,13000,0.000054,Biography,Drama
1618,David Frankel,234.0,0.000064,"[Comedy, Drama, Romance]",Meryl Streep,Hope Springs,34258,178.0,English,0.000030,2012.0,6.3,0,0.000034,Comedy,Drama
410,Nancy Meyers,187.0,0.000113,"[Comedy, Drama, Romance]",Meryl Streep,It's Complicated,69860,214.0,English,0.000085,2009.0,6.6,0,0.000028,Comedy,Drama
2781,Phyllida Lloyd,331.0,0.000030,"[Biography, Drama, History]",Meryl Streep,The Iron Lady,82327,350.0,English,0.000013,2011.0,6.4,18000,0.000017,Biography,Drama
1925,Stephen Daldry,174.0,0.000042,"[Drama, Romance]",Meryl Streep,The Hours,102123,660.0,English,0.000025,2002.0,7.6,0,0.000017,Drama,Romance
3135,Robert Altman,211.0,0.000020,"[Comedy, Drama, Music]",Meryl Streep,A Prairie Home Companion,19655,280.0,English,0.000010,2006.0,6.8,683,0.000010,Comedy,Drama
1106,Curtis Hanson,42.0,0.000047,"[Action, Adventure, Crime, Thriller]",Meryl Streep,The River Wild,32544,69.0,English,0.000045,1994.0,6.3,0,0.000002,Action,Adventure
1674,Carl Franklin,64.0,0.000023,[Drama],Meryl Streep,One True Thing,9283,112.0,English,0.000030,1998.0,7.0,592,-0.000007,Drama,Drama
1483,Robert Redford,227.0,0.000015,"[Drama, Thriller, War]",Meryl Streep,Lions for Lambs,41170,298.0,English,0.000035,2007.0,6.2,0,-0.000020,Drama,Thriller

In [75]:
Leo_Caprio = movies.loc[movies.actor_1_name=="Leonardo DiCaprio"]
Leo_Caprio

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
26,James Cameron,315.0,0.000659,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,0.000200,1997.0,7.7,26000,0.000459,Drama,Romance
97,Christopher Nolan,642.0,0.000293,"[Action, Adventure, Sci-Fi, Thriller]",Leonardo DiCaprio,Inception,1468200,2803.0,English,0.000160,2010.0,8.8,175000,0.000133,Action,Adventure
911,Steven Spielberg,194.0,0.000164,"[Biography, Crime, Drama]",Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,0.000052,2002.0,8.0,15000,0.000112,Biography,Crime
296,Quentin Tarantino,765.0,0.000163,"[Drama, Western]",Leonardo DiCaprio,Django Unchained,955174,1193.0,English,0.000100,2012.0,8.5,199000,0.000063,Drama,Western
179,Alejandro G. Iñárritu,556.0,0.000184,"[Adventure, Drama, Thriller, Western]",Leonardo DiCaprio,The Revenant,406020,1188.0,English,0.000135,2015.0,8.1,190000,0.000049,Adventure,Drama
452,Martin Scorsese,490.0,0.000128,"[Mystery, Thriller]",Leonardo DiCaprio,Shutter Island,786092,964.0,English,0.000080,2010.0,8.1,53000,0.000048,Mystery,Thriller
361,Martin Scorsese,352.0,0.000132,"[Crime, Drama, Thriller]",Leonardo DiCaprio,The Departed,873649,2054.0,English,0.000090,2006.0,8.5,29000,0.000042,Crime,Drama
50,Baz Luhrmann,490.0,0.000145,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,0.000105,2013.0,7.3,115000,0.000040,Drama,Romance
3476,Baz Luhrmann,490.0,0.000145,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,0.000105,2013.0,7.3,115000,0.000040,Drama,Romance
2757,Baz Luhrmann,106.0,0.000046,"[Drama, Romance]",Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,0.000015,1996.0,6.8,10000,0.000032,Drama,Romance
1422,Randall Wallace,83.0,0.000057,"[Action, Adventure]",Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,0.000035,1998.0,6.4,0,0.000022,Action,Adventure
308,Martin Scorsese,606.0,0.000117,"[Biography, Comedy, Crime, Drama]",Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,0.000100,2013.0,8.2,138000,0.000017,Biography,Comedy
1453,Clint Eastwood,392.0,0.000037,"[Biography, Crime, Drama]",Leonardo DiCaprio,J. Edgar,102728,279.0,English,0.000035,2011.0,6.6,16000,0.000002,Biography,Crime
257,Martin Scorsese,267.0,0.000103,"[Biography, Drama]",Leonardo DiCaprio,The Aviator,264318,799.0,English,0.000110,2004.0,7.5,0,-0.000007,Biography,Drama
2067,Jerry Zaks,45.0,0.000013,[Drama],Leonardo DiCaprio,Marvin's Room,20163,71.0,English,0.000023,1996.0,6.7,1000,-0.000010,Drama,Drama
990,Danny Boyle,118.0,0.000040,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,The Beach,176169,548.0,English,0.000050,2000.0,6.6,0,-0.000010,Adventure,Drama
1114,Sam Mendes,323.0,0.000023,"[Drama, Romance]",Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,0.000035,2008.0,7.3,0,-0.000012,Drama,Romance
1560,Sam Raimi,63.0,0.000019,"[Action, Thriller, Western]",Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,0.000032,1995.0,6.4,0,-0.000013,Action,Thriller
326,Martin Scorsese,233.0,0.000078,"[Crime, Drama]",Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,0.000100,2002.0,7.5,0,-0.000022,Crime,Drama
641,Ridley Scott,238.0,0.000039,"[Action, Drama, Thriller]",Leonardo DiCaprio,Body of Lies,174248,263.0,English,0.000070,2008.0,7.1,0,-0.000031,Action,Drama
307,Edward Zwick,166.0,0.000057,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,Blood Diamond,400292,657.0,English,0.000100,2006.0,8.0,14000,-0.000043,Adventure,Drama

In [76]:
Brad_Pitt = movies.loc[movies.actor_1_name=="Brad Pitt"]
Brad_Pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
400,Steven Soderbergh,186.0,1.834058e-04,"[Crime, Thriller]",Brad Pitt,Ocean's Eleven,402645,845.0,English,0.000085,2001.0,7.8,0,9.840577e-05,Crime,Thriller
255,Doug Liman,233.0,1.863361e-04,"[Action, Comedy, Crime, Romance, Thriller]",Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,0.000120,2005.0,6.5,0,6.633610e-05,Action,Comedy
940,Neil Jordan,120.0,1.052646e-04,"[Drama, Fantasy, Horror]",Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,0.000060,1994.0,7.6,11000,4.526461e-05,Drama,Fantasy
470,David Ayer,406.0,8.570712e-05,"[Action, Drama, War]",Brad Pitt,Fury,303185,701.0,English,0.000068,2014.0,7.6,82000,1.770712e-05,Action,Drama
254,Steven Soderbergh,198.0,1.255316e-04,"[Crime, Thriller]",Brad Pitt,Ocean's Twelve,284852,627.0,English,0.000110,2004.0,6.4,0,1.553163e-05,Crime,Thriller
2204,Alejandro G. Iñárritu,285.0,3.430077e-05,[Drama],Brad Pitt,Babel,243799,908.0,English,0.000025,2006.0,7.5,0,9.300771e-06,Drama,Drama
2682,Andrew Dominik,414.0,1.493857e-05,"[Crime, Thriller]",Brad Pitt,Killing Them Softly,111625,369.0,English,0.000015,2012.0,6.2,20000,-6.143000e-08,Crime,Thriller
2898,Tony Scott,122.0,1.228150e-05,"[Action, Crime, Drama, Romance, Thriller]",Brad Pitt,True Romance,163492,460.0,English,0.000013,1993.0,8.0,15000,-7.185000e-07,Action,Crime
2333,Angelina Jolie Pitt,131.0,5.310090e-07,"[Drama, Romance]",Brad Pitt,By the Sea,7976,61.0,English,0.000010,2015.0,5.3,0,-9.468991e-06,Drama,Romance
1490,Terrence Malick,584.0,1.330332e-05,"[Drama, Fantasy]",Brad Pitt,The Tree of Life,136367,975.0,English,0.000032,2011.0,6.7,39000,-1.869668e-05,Drama,Fantasy
101,David Fincher,362.0,1.274908e-04,"[Drama, Fantasy, Romance]",Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,0.000150,2008.0,7.8,23000,-2.250920e-05,Drama,Fantasy
683,David Fincher,315.0,3.702340e-05,[Drama],Brad Pitt,Fight Club,1347461,2968.0,English,0.000063,1999.0,8.8,48000,-2.597660e-05,Drama,Drama
1722,Andrew Dominik,273.0,3.904982e-06,"[Biography, Crime, Drama, History, Western]",Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,0.000030,2007.0,7.5,0,-2.609502e-05,Biography,Crime
611,Jean-Jacques Annaud,76.0,3.790151e-05,"[Adventure, Biography, Drama, History, War]",Brad Pitt,Seven Years in Tibet,96385,119.0,English,0.000070,1997.0,7.0,0,-3.209849e-05,Adventure,Biography
792,Patrick Gilmore,98.0,2.628832e-05,"[Adventure, Animation, Comedy, Drama, Family, ...",Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,0.000060,2003.0,6.7,880,-3.371168e-05,Adventure,Animation
147,Wolfgang Petersen,220.0,1.332283e-04,[Adventure],Brad Pitt,Troy,381672,1694.0,English,0.000175,2004.0,7.2,0,-4.177165e-05,Adventure,Adventure
382,Tony Scott,142.0,2.687100e-08,"[Action, Crime, Thriller]",Brad Pitt,Spy Game,121259,361.0,English,0.000092,2001.0,7.0,0,-9.197313e-05,Action,Crime

In [77]:
# Write your code for combining the three dataframes here
combined= pd.concat([Meryl_Streep,Brad_Pitt,Leo_Caprio])
combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
1408,David Frankel,208.0,1.247330e-04,"[Comedy, Drama, Romance]",Meryl Streep,The Devil Wears Prada,286178,631.0,English,0.000035,2006.0,6.8,0,8.973296e-05,Comedy,Drama
1575,Sydney Pollack,66.0,8.710000e-05,"[Biography, Drama, Romance]",Meryl Streep,Out of Africa,52339,200.0,English,0.000031,1985.0,7.2,0,5.610000e-05,Biography,Drama
1204,Nora Ephron,252.0,9.412543e-05,"[Biography, Drama, Romance]",Meryl Streep,Julie & Julia,79264,277.0,English,0.000040,2009.0,7.0,13000,5.412543e-05,Biography,Drama
1618,David Frankel,234.0,6.353601e-05,"[Comedy, Drama, Romance]",Meryl Streep,Hope Springs,34258,178.0,English,0.000030,2012.0,6.3,0,3.353601e-05,Comedy,Drama
410,Nancy Meyers,187.0,1.127035e-04,"[Comedy, Drama, Romance]",Meryl Streep,It's Complicated,69860,214.0,English,0.000085,2009.0,6.6,0,2.770347e-05,Comedy,Drama
2781,Phyllida Lloyd,331.0,2.995944e-05,"[Biography, Drama, History]",Meryl Streep,The Iron Lady,82327,350.0,English,0.000013,2011.0,6.4,18000,1.695944e-05,Biography,Drama
1925,Stephen Daldry,174.0,4.159783e-05,"[Drama, Romance]",Meryl Streep,The Hours,102123,660.0,English,0.000025,2002.0,7.6,0,1.659783e-05,Drama,Romance
3135,Robert Altman,211.0,2.033861e-05,"[Comedy, Drama, Music]",Meryl Streep,A Prairie Home Companion,19655,280.0,English,0.000010,2006.0,6.8,683,1.033861e-05,Comedy,Drama
1106,Curtis Hanson,42.0,4.681575e-05,"[Action, Adventure, Crime, Thriller]",Meryl Streep,The River Wild,32544,69.0,English,0.000045,1994.0,6.3,0,1.815748e-06,Action,Adventure
1674,Carl Franklin,64.0,2.320944e-05,[Drama],Meryl Streep,One True Thing,9283,112.0,English,0.000030,1998.0,7.0,592,-6.790560e-06,Drama,Drama
1483,Robert Redford,227.0,1.499807e-05,"[Drama, Thriller, War]",Meryl Streep,Lions for Lambs,41170,298.0,English,0.000035,2007.0,6.2,0,-2.000193e-05,Drama,Thriller
400,Steven Soderbergh,186.0,1.834058e-04,"[Crime, Thriller]",Brad Pitt,Ocean's Eleven,402645,845.0,English,0.000085,2001.0,7.8,0,9.840577e-05,Crime,Thriller
255,Doug Liman,233.0,1.863361e-04,"[Action, Comedy, Crime, Romance, Thriller]",Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,0.000120,2005.0,6.5,0,6.633610e-05,Action,Comedy
940,Neil Jordan,120.0,1.052646e-04,"[Drama, Fantasy, Horror]",Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,0.000060,1994.0,7.6,11000,4.526461e-05,Drama,Fantasy
470,David Ayer,406.0,8.570712e-05,"[Action, Drama, War]",Brad Pitt,Fury,303185,701.0,English,0.000068,2014.0,7.6,82000,1.770712e-05,Action,Drama
254,Steven Soderbergh,198.0,1.255316e-04,"[Crime, Thriller]",Brad Pitt,Ocean's Twelve,284852,627.0,English,0.000110,2004.0,6.4,0,1.553163e-05,Crime,Thriller
2204,Alejandro G. Iñárritu,285.0,3.430077e-05,[Drama],Brad Pitt,Babel,243799,908.0,English,0.000025,2006.0,7.5,0,9.300771e-06,Drama,Drama
2682,Andrew Dominik,414.0,1.493857e-05,"[Crime, Thriller]",Brad Pitt,Killing Them Softly,111625,369.0,English,0.000015,2012.0,6.2,20000,-6.143000e-08,Crime,Thriller
2898,Tony Scott,122.0,1.228150e-05,"[Action, Crime, Drama, Romance, Thriller]",Brad Pitt,True Romance,163492,460.0,English,0.000013,1993.0,8.0,15000,-7.185000e-07,Action,Crime
2333,Angelina Jolie Pitt,131.0,5.310090e-07,"[Drama, Romance]",Brad Pitt,By the Sea,7976,61.0,English,0.000010,2015.0,5.3,0,-9.468991e-06,Drama,Romance
1490,Terrence Malick,584.0,1.330332e-05,"[Drama, Fantasy]",Brad Pitt,The Tree of Life,136367,975.0,English,0.000032,2011.0,6.7,39000,-1.869668e-05,Drama,Fantasy
101,David Fincher,362.0,1.274908e-04,"[Drama, Fantasy, Romance]",Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,0.000150,2008.0,7.8,23000,-2.250920e-05,Drama,Fantasy
683,David Fincher,315.0,3.702340e-05,[Drama],Brad Pitt,Fight Club,1347461,2968.0,English,0.000063,1999.0,8.8,48000,-2.597660e-05,Drama,Drama
1722,Andrew Dominik,273.0,3.904982e-06,"[Biography, Crime, Drama, History, Western]",Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,0.000030,2007.0,7.5,0,-2.609502e-05,Biography,Crime
611,Jean-Jacques Annaud,76.0,3.790151e-05,"[Adventure, Biography, Drama, History, War]",Brad Pitt,Seven Years in Tibet,96385,119.0,English,0.000070,1997.0,7.0,0,-3.209849e-05,Adventure,Biography
792,Patrick Gilmore,98.0,2.628832e-05,"[Adventure, Animation, Comedy, Drama, Family, ...",Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,0.000060,2003.0,6.7,880,-3.371168e-05,Adventure,Animation
147,Wolfgang Petersen,220.0,1.332283e-04,[Adventure],Brad Pitt,Troy,381672,1694.0,English,0.000175,2004.0,7.2,0,-4.177165e-05,Adventure,Adventure
382,Tony Scott,142.0,2.687100e-08,"[Action, Crime, Thriller]",Brad Pitt,Spy Game,121259,361.0,English,0.000092,2001.0,7.0,0,-9.197313e-05,Action,Crime
26,James Cameron,315.0,6.586723e-04,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,0.000200,1997.0,7.7,26000,4.586723e-04,Drama,Romance
97,Christopher Nolan,642.0,2.925689e-04,"[Action, Adventure, Sci-Fi, Thriller]",Leonardo DiCaprio,Inception,1468200,2803.0,English,0.000160,2010.0,8.8,175000,1.325689e-04,Action,Adventure
911,Steven Spielberg,194.0,1.644352e-04,"[Biography, Crime, Drama]",Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,0.000052,2002.0,8.0,15000,1.124352e-04,Biography,Crime
296,Quentin Tarantino,765.0,1.628046e-04,"[Drama, Western]",Leonardo DiCaprio,Django Unchained,955174,1193.0,English,0.000100,2012.0,8.5,199000,6.280465e-05,Drama,Western
179,Alejandro G. Iñárritu,556.0,1.836359e-04,"[Adventure, Drama, Thriller, Western]",Leonardo DiCaprio,The Revenant,406020,1188.0,English,0.000135,2015.0,8.1,190000,4.863592e-05,Adventure,Drama
452,Martin Scorsese,490.0,1.279684e-04,"[Mystery, Thriller]",Leonardo DiCaprio,Shutter Island,786092,964.0,English,0.000080,2010.0,8.1,53000,4.796841e-05,Mystery,Thriller
361,Martin Scorsese,352.0,1.323734e-04,"[Crime, Drama, Thriller]",Leonardo DiCaprio,The Departed,873649,2054.0,English,0.000090,2006.0,8.5,29000,4.237344e-05,Crime,Drama
50,Baz Luhrmann,490.0,1.448128e-04,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,0.000105,2013.0,7.3,115000,3.981280e-05,Drama,Romance
3476,Baz Luhrmann,490.0,1.448128e-04,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,0.000105,2013.0,7.3,115000,3.981280e-05,Drama,Romance
2757,Baz Luhrmann,106.0,4.633873e-05,"[Drama, Romance]",Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,0.000015,1996.0,6.8,10000,3.183873e-05,Drama,Romance
1422,Randall Wallace,83.0,5.687637e-05,"[Action, Adventure]",Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,0.000035,1998.0,6.4,0,2.187637e-05,Action,Adventure
308,Martin Scorsese,606.0,1.168667e-04,"[Biography, Comedy, Crime, Drama]",Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,0.000100,2013.0,8.2,138000,1.686673e-05,Biography,Comedy
1453,Clint Eastwood,392.0,3.730495e-05,"[Biography, Crime, Drama]",Leonardo DiCaprio,J. Edgar,102728,279.0,English,0.000035,2011.0,6.6,16000,2.304950e-06,Biography,Crime
257,Martin Scorsese,267.0,1.026088e-04,"[Biography, Drama]",Leonardo DiCaprio,The Aviator,264318,799.0,English,0.000110,2004.0,7.5,0,-7.391173e-06,Biography,Drama
2067,Jerry Zaks,45.0,1.278251e-05,[Drama],Leonardo DiCaprio,Marvin's Room,20163,71.0,English,0.000023,1996.0,6.7,1000,-1.021749e-05,Drama,Drama
990,Danny Boyle,118.0,3.977860e-05,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,The Beach,176169,548.0,English,0.000050,2000.0,6.6,0,-1.022140e-05,Adventure,Drama
1114,Sam Mendes,323.0,2.287781e-05,"[Drama, Romance]",Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,0.000035,2008.0,7.3,0,-1.212219e-05,Drama,Romance
1560,Sam Raimi,63.0,1.863654e-05,"[Action, Thriller, Western]",Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,0.000032,1995.0,6.4,0,-1.336346e-05,Action,Thriller
326,Martin Scorsese,233.0,7.767964e-05,"[Crime, Drama]",Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,0.000100,2002.0,7.5,0,-2.232036e-05,Crime,Drama
641,Ridley Scott,238.0,3.938044e-05,"[Action, Drama, Thriller]",Leonardo DiCaprio,Body of Lies,174248,263.0,English,0.000070,2008.0,7.1,0,-3.061956e-05,Action,Drama
307,Edward Zwick,166.0,5.736626e-05,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,Blood Diamond,400292,657.0,English,0.000100,2006.0,8.0,14000,-4.263374e-05,Adventure,Drama

In [78]:
# Write your code for grouping the combined dataframe here
combined_by_segment= combined.groupby("actor_1_name")

In [79]:
# Write the code for finding the mean of critic reviews and audience reviews here
combined.isnull().sum()

director_name             0
num_critic_for_reviews    0
gross                     0
genres                    0
actor_1_name              0
movie_title               0
num_voted_users           0
num_user_for_reviews      0
language                  0
budget                    0
title_year                0
imdb_score                0
movie_facebook_likes      0
Profit                    0
genre_1                   0
genre_2                   0
dtype: int64

In [80]:
combined_by_segment["num_user_for_reviews"].mean()

actor_1_name
Brad Pitt            742.352941
Leonardo DiCaprio    914.476190
Meryl Streep         297.181818
Name: num_user_for_reviews, dtype: float64

In [81]:
combined_by_segment["num_critic_for_reviews"].mean()

actor_1_name
Brad Pitt            245.000000
Leonardo DiCaprio    330.190476
Meryl Streep         181.454545
Name: num_critic_for_reviews, dtype: float64

**Checkpoint 6:** `Leonardo` has aced both the lists!